# Generated by Django 6.0 on 2026-03-25 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_alter_ciudad_options_imageninmueble'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageninmueble',
            name='descripcion',
            field=models.CharField(default='', max_length=255),
        ),
    ]
