# Generated by Django 6.0 on 2026-03-25 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_agente'),
    ]

    operations = [
        migrations.AddField(
            model_name='inmueble',
            name='agente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='portal.agente'),
        ),
    ]
